configured_by = ("configured",)
uses = ("use", "uses")
contains = ("has", "have", "contain", "contains", "stores")
has = contains + uses
is_created_as = "is-created-as"
runs = ("run", "runs", "running")
with_ = ("with",)
wraps = ("wraps",)
connects = ("connects",)
loads = ("loads",)
shows = ("shows", "displays")
supports = ("supports",)
provides = ("provides",)
